Add X11 as a dependency under UNIX.
Since the latest ArchLinux updates TSC fails to compile otherwise
with X11-related linking errors:

/usr/bin/ld: CMakeFiles/tsc.dir/src/gui/generic.cpp.o: undefined reference to symbol 'XGetSelectionOwner'
/usr/lib/libX11.so.6: error adding symbols: DSO missing from command line